name: Checkers

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
  schedule:
  - cron: '30 12 * * *'
  workflow_dispatch:

jobs:

  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: JustinBeckwith/linkinator-action@v1.11.0
      with:
        linksToSkip: '^https://github.com/ ^https://opensource.org/'
        paths: '*.md doc/*.md formatter-*/*.md'

  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tbroadley/spellchecker-cli-action@v1
      with:
        dictionaries: '.github/dictionary.txt'
        files: '*.md doc/*.md formatter-*/*.md'
