name: Smoke Test

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        node-version: [ 20, 22, 23 ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: git config user.email "user@example.com" && git config user.name "User" && npm version 0.1.2
    - run: npm pack
    - run: npm exec --yes -- del-cli node_modules .npmrc npm-shrinkwrap.json package.json package-lock.json
    - run: npm install markdownlint-cli2-0.1.2.tgz
    - run: node_modules/.bin/markdownlint-cli2 README.md
    - run: npm clean-install
    - run: node_modules/.bin/markdownlint-cli2 README.md
    - run: git clean -dfx && git restore .
    - run: npm exec --yes -- midnight-smoker test-invoke-as-cli
      if: matrix.os != 'windows-latest'
